/* Release #4.9.10.2, see https://dataconsole.kruxdigital.com/kruxjs_release_notes/#4.9.10.2*/
/* File modified at 02/07/2012 04:06:46 PM PST. md5 = 969f0f38873794224f7df52922b60428 */
/* Copyright 2010-2012 Krux Digital, Inc. All Rights Reserved. No permission is granted to use, copy or modify this code. */
!window.krux_js&&-1<location.search.indexOf("krux_release")?function(){var h=location.search.match(/krux_release=(dev|stage)/);if(h)window.krux_js="http://kruxcontent-"+h[1]+".s3.amazonaws.com/krux.js?"+Math.random();else if(h=location.search.match(/krux_release=([\w.]+)/))window.krux_js="//cdn.krxd.net/kruxcontent/releases/krux-"+h[1]+".js";if(window.krux_js){window.console&&console.log&&console.log("Using "+window.krux_js);h=document.createElement("script");h.src=window.krux_js;var g=document.getElementsByTagName("script")[0];
g.parentNode.insertBefore(h,g)}}():window.KRUX||function(h,g,l){function y(a,b,d){if(b.rules)for(var a="tag_"+b.id,e=0;e<b.rules.length;++e){var f=b.rules[e],g=a+"_rule_"+e,f=[f.name,f.actual,f.operator,f.value,f.pass?"pass":"fail"].join("|");d[g]=f}}function M(a){q("config_requests");if(h.superTag.config)b.configOnload(h.superTag.config);else{var c={pubid:h.pubid,site:h.site,callback:"KRUX.configOnload"};"unpublished"==b.getRequestVal("krux_config")&&(c.state="unpublished",c.cache="false",c.cb=Math.random());
c=k.configUrl+"?"+A(c);b.configStartTime=(new Date).getTime();E(c,!a)}}function N(){var a=!1;b.ST.config?w.each(b.ST.config.tags||[],function(b){return w.each(b.rules||[],function(b){if("country"===b.name)return a=!0,w.breaker})}):a=!0;return a}var v={pubid:"",site:"",section:"",subsection:"",channels:"",async:!1,autoCollect:!0,autoInit:!0,pixelTime:1E3,reportErrors:!0,allTagsOffsite:!1,userAttributes:{},pageAttributes:{},trackSocial:!1};h||(h=v,g.KRUXSetup=h);for(var B in v)v.hasOwnProperty(B)&&
"undefined"==typeof h[B]&&(h[B]=v[B]);var C=(0===location.protocol.indexOf("http")?location.protocol:"http:")+"//services.krxd.net/",b={_kvs:{},_parameters:{},backgroundGets:[],blockUrl:C+"block.gif",collectors:[],collectUrl:C+"pixel.gif",socialUrl:C+"social.gif",eventUrl:C+"event.gif",eventsUrl:C+"stats",geo:{},geoUrl:C+"geoip?root_name=KRUX.geo",configCache:"na",debugLevel:0,errorUrl:C+"/jserror",kruxIframeUrl:"//cdn.krxd.net/kruxcontent/krux_iframe.html?",loadedScripts:[],onloadCalled:!1,predbg:"",
release:"4.9.10.2",scriptTimeout:2E4,sessionViews:0,sTag:/^<script((?:\s+[\w\-:]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/},w=window.KRUX2=function(){function a(a){return!!(""===a||a&&a.charCodeAt&&a.substr)}function c(a,b){return function(){return a.apply(b,arguments)}}function d(){function a(){for(var c=0,d=arguments.length;c<d;++c)b.push(arguments[c]);return a}var b=[];a.data=function(){return b.join("")};return a}function e(a,b,c){var d=a.tagName,f=a.attributes||{},a=a.children||
[],b=b||[],c=c||0,g=i[d];b("<",d);for(var h in f)b(" ",h,'="',f[h],'" ');if(g)return b("/>");b(">");f=0;for(h=a.length;f<h;++f)e(a[f],b,c+1);g||b("</",d,">")}function f(b,c){a(b)&&(b={tagName:b,attributes:c});var f=new d;e(b,f);return f.data()}function h(a){var b=document.createElement("div");b.innerHTML=a;return b.childNodes}function l(a){var c=f.apply(null,arguments);b.literate()?document.write(c):document.body.appendChild(h(c)[0])}var s={},k=s.breaker={};s.each=function(a,b,c){if(a)if(a.length===
+a.length)for(var d=0,e=a.length;d<e;d++){if(d in a&&b.call(c,a[d],d,a)===k)return k}else for(d in a)if(a.hasOwnProperty(d)&&b.call(c,a[d],d,a)===k)return k;return null};var i=new function(a){for(var b=0;b<a.length;b++)this[a[b]]=!0}("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed".split(",")),j={},I=s.on=function(b,d,e,f){a(b)&&(f=e,e=d,d=b,b=null);f&&(e=c(e,f));b?b.addEventListener?b.addEventListener(d,e,!1):b.attachEvent&&b.attachEvent("on"+d,e):(j[d]||(j[d]=[])).push(e)},
n=s.off=function(b,c,d){a(b)&&(d=c,c=b,b=null);b&&(b.removeEventListener?b.removeEventListener(c,d,!1):b.detachEvent&&b.detachEvent(c,d))},o={},m=s.fire=function(a,b){var b=b||{},c=j[a]||[];b.type=a;o[a]=b;for(var d=0,e=c.length;d<e;++d)c[d](b)},p=s.hasFired=function(a){return o[a]},u=s.fireOnce=function(a,c){if(p(a)){if(b.debugLevel)throw"Double fireOnce";}else m(a,c)},K=s.waitFor=function(a,b,d){d&&(b=c(b,d));(d=p(a))?b(d):I(a,b)};s.waitForAll=function(b,d,e){function f(){if(!h){for(var a=0,c=b.length;a<
c;++a)if(!p(b[a]))return;h=!0;d()}}a(b)&&(b=b.split(" "));if(a(d))var g=d,d=function(){u(g,e)};else e&&(d=c(d,e));for(var h=!1,G=0,s=b.length;G<s;++G)K(b[G],f)};s.loadKuid=function(){function a(){u("kuid",{value:s.kuid})}function b(){function c(b){"http://cdn.krxd.net"===b.origin&&(n(window,"message",c),g.localStorage.kuid=s.kuid=b.data,a())}I(window,"message",c);l("iframe",{src:"//cdn.krxd.net/kruxcontent/xdomain.html",style:"display: none"})}s.kuid=g.localStorage&&g.localStorage.kuid;s.kuid?a():
window.localStorage&&window.postMessage?b():a()};return s}(),n={};b._parameters=n;var m={};m.ua=navigator.userAgent.toLowerCase();v=m.ua.match(/(webkit)[ \/]([\w.]+)/)||m.ua.match(/(opera)(?:.*version)?[ \/]([\w.]+)/)||m.ua.match(/(msie) ([\w.]+)/)||0>m.ua.indexOf("compatible")&&m.ua.match(/(mozilla)(?:.*? rv:([\w.]+))?/)||["","",0];m.browser=v[1];m.version=parseFloat((v[2]||"0").match(/^[0-9]+[.0-9]*/)[0],10);m.msie="msie"==v[1];m.mozilla="mozilla"==v[1];m.webkit="webkit"==v[1];m.opera="opera"==
v[1];m.gecko=-1!=m.ua.indexOf("gecko/");m.chrome=!!g.chrome;v=g.screen.colorDepth;B=g.screen;m.res=8==v||16==v||24==v||32==v?[B.width,B.height,v].join("x"):[B.width,B.height].join("x");b.is=b._is=m;b.is.awesome=!0;b.is.performance=g.performance&&g.performance.timing&&!(b.is.gecko&&9>b.is.version);b._=function(a){return l.getElementById(a)};var J=function(a,c,d){a=(a||"")+c.replace(/[^0-9A-Za-z_]/g,"_");return d?(d=b.toS(d).substring(0,542),n[a]=d,!0):n[a]},L=function(a,c){for(var d=b.keyValues(a),
e=0;e<d.keys.length;e++)J(c,d.keys[e],d.values[e])};b.context=function(a,b){return J("_kcp_",a,b)};b.pageAttribute=function(a,b){return J("_kpa_",a,b)};b.userAttribute=function(a,b){return J("_kua_",a,b)};b.afterLoadCallback=function(a){if(b.onloadCalled)return a();b.afterLoadFunctions||(b.afterLoadFunctions=[]);b.afterLoadFunctions.push(a);return null};b.trackSocial=function(){b.trackFacebook();b.trackTwitter()};b.trackFacebook=function(){g.FB&&g.FB.Event&&g.FB.Event.subscribe&&(g.FB.Event.subscribe("edge.create",
function(a){var c=b.clone(n);c._ksoc_t="fb";c._ksoc_e="like";c._ksoc_url=a;D(h.socialUrl||b.socialUrl,c);q("facebook.like")}),g.FB.Event.subscribe("edge.remove",function(a){var c=b.clone(n);c._ksoc_t="fb";c._ksoc_e="unlike";c._ksoc_url=a;D(h.socialUrl||b.socialUrl,c);q("facebook.unlike")}),g.FB.Event.subscribe("message.send",function(a){var c=b.clone(n);c._ksoc_t="fb";c._ksoc_e="send";c._ksoc_url=a;D(h.socialUrl||b.socialUrl,c);q("facebook.send")}))};b.trackTwitter=function(){g.twttr&&g.twttr.events&&
g.twttr.events.bind&&g.twttr.events.bind("tweet",function(a){if(a){var c;a.target&&"IFRAME"==a.target.nodeName&&(c=b.getRequestVal("url","",H(a.target)));a=b.clone(n);a._ksoc_t="twttr";a._ksoc_e="tweet";a._ksoc_url=c;D(h.socialUrl||b.socialUrl,a);q("twitter.tweet")}})};b.appendTag=function(a,b){var d=l.createElement(a),e;for(e in b)"string"==typeof e&&(d[e]=b[e]);if((e=l.getElementsByTagName("head"))&&e[0])e[0].appendChild(d);else{e=l.getElementsByTagName("script");for(var f=0,g=e.length;f<g;f++)if(e[f]&&
e[f].parentNode){e[f].parentNode.insertBefore(d,e[f]);break}}return d};b.bool=function(a){return"string"==typeof a&&"false"===a.toLowerCase()||"0"===a?!1:!!a};b.buildElement=function(a,c){for(var d=l.createElement(a),e=b.keyValues(c),f=0;f<e.keys.length;f++){var g,h;try{g=e.keys[f].replace(/[^A-Za-z0-9_]/g,"_").toLowerCase(),h=b.toS(e.values[f]).replace(/"/g,"&quot;"),d.setAttribute(g,h)}catch(s){}}return d};b.buildAttributes=function(a){for(var c=[],a=b.keyValues(a),d=0;d<a.keys.length;d++){var e,
f;try{e=a.keys[d].replace(/[^A-Za-z0-9_]/g,"_").toLowerCase(),f=b.toS(a.values[d]).replace(/"/g,"&quot;"),c.push(e+'="'+f+'"')}catch(g){}}return c.join(" ")};b.collectBeacon=function(){var a=r&&r.geo||null;a&&(n.geo_country=a.COUNTRY,n.geo_region=a.REGION,n.geo_city=a.CITY,n.geo_dma=a.DMA);if(r&&r.tags)for(var a=0,c=r.tags.length;a<c;a++)r.tags[a].started&&(k.loadSequence=k.loadSequence?k.loadSequence+1:1,n["kplt"+k.loadSequence]=r.tags[a].id,q("tags_loaded")),y(a,r.tags[a],n);n._knifr=g.frames.length;
n._kpid=h.pubid;i.realtimeSegments();n._krtsegs=i._rsegments;b.context("s",h.site);b.context("sc",h.section);b.context("ssc",h.subSection);var d=g.performance;b.is.performance&&(n.t_navigation_type=d.navigation.type,a=function(a,b){if(!d.timing[a]||!d.timing[b])return-1;var c=d.timing[b]-d.timing[a];return 0>c||3E4<c?-1:c},n.t_dns=a("domainLookupStart","domainLookupEnd"),n.t_tcp=a("connectStart","connectEnd"),n.t_http_request=a("requestStart","responseStart"),n.t_http_response=a("responseStart","responseEnd"),
n.t_content_ready=a("navigationStart","domInteractive"),n.t_window_load=a("navigationStart","loadEventStart"),n.t_redirect=a("redirectStart","redirectEnd"));D(h.collectUrl||b.collectUrl,n);O();w.fireOnce("collect_beacon")};b.clone=function(a){if("object"==typeof a&&null!==a){var c=new a.constructor,d;for(d in a)a.hasOwnProperty(d)&&(c[d]=b.clone(a[d]));return c}return a};(function(){function a(a,b){a._done||(a(b),a._done=1)}function c(a){var b;if("object"==typeof a)for(var c in a)a[c]&&(b={name:c,
url:a[c]});else b=a.split("/"),b=b[b.length-1],c=b.indexOf("?"),b={name:-1!=c?b.substring(0,c):b,url:a};return(a=m[b.name])&&a.url===b.url?a:m[b.name]=b}function d(a,b){if(a){"object"==typeof a&&(a=[].slice.call(a));for(var c=0;c<a.length;c++)b.call(a,a[c],c)}}function e(a){return"[object Function]"==Object.prototype.toString.call(a)}function f(a){var a=a||m,b=!1,c=0,d;for(d in a)if(a.hasOwnProperty(d)){if(a[d].state!=t)return!1;b=!0;c++}return b||0===c}function h(a){a.state=K;d(a.onpreload,function(a){a.call()})}
function k(a,b,c){b.state||(b.state=q,b.node=a,b.onpreload=[],E(b.url,!1,function(){h(b)},c,a,"cache"))}function s(b,c,e){if(c.state==t&&e)return e(b);if(c.state==v)return u.ready(c.name,e);if(c.state==q)return c.onpreload.push(function(){s(c,e)});c.state=v;c.node=b;E(c.url,!1,function(){c.state=t;e&&e(b);d(o[c.name],function(c){a(c,b)});j&&f()&&d(o.ALL,function(c){a(c,b)})});return!0}var i,j,n=[],I=[],o={},m={},p=!0===l.createElement("script").async||"MozAppearance"in l.documentElement.style||g.opera,
r=g.head_conf&&g.head_conf.KRUXhead||"KRUXhead",u=g[r]=g[r]||function(){u.ready.apply(null,arguments)},K=0,q=1,v=2,t=3;u.js=p?function(){var b=arguments,g=b[b.length-1],h=[],G=b[0],b=[].slice.call(b,1);e(g)||(g=null);d(b,function(d,e){d!=g&&(d=c(d),h.push(d),s(G,d,g&&e==b.length-2?function(){f(h)&&a(g,G)}:null))});return u}:function(){var a=arguments,b=a[0],f=[].slice.call(a,2),g=f[0];if(!i)return I.push(function(){u.js.apply(null,a)}),u;g?(d(f,function(a){e(a)||k(b,c(a))}),s(b,c(a[1]),e(g)?g:function(){u.js.apply(null,
f)})):s(b,c(a[1]));return u};u.ready=function(b,c){if("dom"==b)return j?a(c):n.push(c),u;e(b)&&(c=b,b="ALL");var d=m[b];if(d&&d.state==t||"ALL"==b&&f()&&j)return a(c),u;(d=o[b])?d.push(c):o[b]=[c];return u};u.ready("dom",function(){i&&f()&&d(o.ALL,function(b){a(b)});u.feature&&u.feature("domloaded",!0)});setTimeout(function(){i=!0;d(I,function(a){a()})},0);b.fireReady=function(){j||(j=!0,d(n,function(b){a(b)}))}})(document);(function(){var a=/^<([\w:]+)((?:\s+[\w\-:]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,
c=/^<\/([\w:]+)[^>]*>/,d=/([\w:]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,e=function(a){for(var b={},a=a.split(","),c=0;c<a.length;c++)b[a[c]]=!0;return b},f=e("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed"),g=e("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,table,tbody,td,tfoot,th,thead,tr,ul"),h=e("a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var"),
s=e("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),l=e("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),k=e("script,style");b.HTMLParser=function(e,i,j){function n(a,c,e,k){if(g[c]||0===c.toLowerCase().indexOf("fb:"))for(;t.last()&&h[t.last()];)o("",t.last());s[c]&&t.last()==c&&o("",c);(k=f[c]||!!k)||t.push(c);if(j.start){var p=[];e.replace(d,function(a,b,c,d,e){a=c?c:d?d:e?e:l[b]?b:"";p.push({name:b,value:a,escaped:a.replace(/(^|[^\\])"/g,
'$1\\"')})});b.predbg+=" ";j.start&&-1==j.start(c,p,k,m,i,x)&&(i="");k&&(b.predbg=b.predbg.substr(0,b.predbg.length-1))}}function o(a,c){var d=0;if(c)for(d=t.length-1;0<=d&&!(t[d]==c);d--);if(0<=d){for(var e=t.length-1;e>=d;e--)j.end&&(-1==j.end(t[e],m,i)&&(i=""),b.predbg=b.predbg.substr(0,b.predbg.length-1));t.length=d}}var m=e,u="",p,r,q,t=[],v=i,w=0,x=this;t.last=function(){return this[this.length-1]};this.parse=function(b,d,e){m=b||m;"string"==typeof u&&(d=u+d);u="";for(v=i=d;i;){r=!0;if(!t.last()||
!k[t.last()]){if(0===i.indexOf("<\!--"))p=i.indexOf("--\>"),0<=p&&(e.comment&&-1==e.comment(i.substring(4,p),m,i)&&(i=""),i=i.substring(p+3),r=!1);else if(0===i.indexOf("</")){if(q=i.match(c))i=i.substring(q[0].length),q[0].replace(c,o),r=!1}else if(0===i.indexOf("<")&&(q=i.match(a)))i=i.substring(q[0].length),q[0].replace(a,n),r=!1;r&&(p=i.indexOf("<"),b=0>p?i:i.substring(0,p),i=0>p?"":i.substring(p),e.chars&&-1==e.chars(b,m,i)&&(i=""))}else if(-1!=i.indexOf("</"+t.last()+">")){var f=t.last();i=
i.replace(RegExp("([^\x00]*?)</"+t.last()+"[^>]*>","m"),function(a,b){b=b.replace(/<\!--(.*?)--\>/g,"$1").replace(/<!\[CDATA\[(.*?)\]\]>/g,"$1");"script"==t.last()&&w++;"script"==f&&t.pop();e.chars&&-1==e.chars(b,m,i,w,1)&&(i="");"script"==f&&t.push(f);"script"==t.last()&&w--;return""});o("",t.last())}if(i==v)return u=i;v=i}return""};this.setUnparsed=function(a){if("string"==typeof a||"number"==typeof a)u+=a+"";return u};i.length&&this.parse(m,i,j)}})();var x={blocklist:[],urlDisabled:!1};b.CM=x;
l.__krux_write_real=l.write;l.__krux_writeln=l.writeln;l.__krux_write=function(a){if(b.literate())return l.__krux_write_real(a);if(g.KRUXTest&&g.KRUXTest.throwDebugErrors)throw"FAILED to write to page, it's too late. rs="+l.readyState+": "+a;return!1};var o={scriptStack:[],insideStack:[],scriptParse:0,_src:void 0};b.tagWriter=o;o.setup=function(){o.setup.called||(o.setup.called=!0,l.write=l.writeln=o.docWrite=function(a,c){function d(a,c,i,k,j,s){for(var F={},n=a.toLowerCase(),m=0,q=c.length;m<q;m++){if(!h&&
("src"==c[m].name.toLowerCase()||"krux_deferred_src"==c[m].name.toLowerCase())&&x.checkBL(c[m].value))F.blocked_src=c[m].value,F.krux_blocked="1",x.recordBlock(c[m].value);else{if(("krux_deferred_src"==c[m].name.toLowerCase()||"src"==c[m].name.toLowerCase())&&"script"==n)o._src=c[m].value;F[c[m].name]=c[m].value}if(F.krux_blocked&&("img"==n||"iframe"==n))F.style="display: none"}if("script"==a){if((c=H(F))&&b.literate()){l.__krux_write('<script src="'+c+'"><\/script>');return}if(c){s.setUnparsed(j);
g.KRUXhead.js(void 0,c,function(){s.parse(k||o.node,"",{start:d,end:e,chars:f})});return}o.scripts++}a=b.buildElement(a,F);j=o.node;try{p.last()?j.appendChild(a):j.parentNode.insertBefore(a,j.nextSibling)}catch(r){}p.push(i?0:1);o.node=a}function e(){p.pop();p.last()&&(o.node=o.node.parentNode)}function f(a){var b=o.node;if(p.last())try{p.push(0),b.appendChild(l.createTextNode(a)),p.pop()}catch(c){b.text+=a}else try{o.node=b.parentNode.insertBefore(l.createTextNode(a),b.nextSibling)}catch(d){}}var h=
1>x.blocklist.length||x.urlDisabled;if(h&&b.literate())l.__krux_write(a);else if(a+="",0!==a.length){if(c){var i=o.node,k=p;o.node=c;p.length=0;p.push(1)}else{var j=l.getElementsByTagName("script");j.length!=o.scripts&&(o.scripts=j.length,o.node=j[j.length-1],p.push(0))}o.parser?o.parser.parse(c,a,{start:d,end:e,chars:f}):o.parser=new b.HTMLParser(c,a,{start:d,end:e,chars:f});c&&(o.node=i,p=k)}})};x.addToBL=function(a){x.blocklist.push(a.toLowerCase())};g.addToBlocklist=x.addToBL;x.checkBL=function(a){if("string"!=
typeof a)return 0;for(var a=a.toLowerCase().replace(/\?.+$/,""),b=0;b<x.blocklist.length;b++)if(a.match(RegExp(x.blocklist[b])))return 1;return 0};x.recordBlock=function(a){q("counter_measure_blocks");D(b.blockUrl+"?"+A({_kpid:h.pubid,_kcp_s:h.site,_kcp_sc:h.section,_kcp_ssc:h.subSection,_kurl_0:a}))};b.configOnload=function(a){r=a;b.ST.config=a;q("config_request_time",(new Date).getTime()-b.configStartTime,"ms");if(a.blocklist)for(var c=0;c<a.blocklist.length;c++)g.addToBlocklist(a.blocklist[c].pattern);
a.params&&(void 0!==a.params.max_slot_time&&(h.pixelTime=a.params.max_slot_time),h.autoCollect=b.bool(a.params.capture_leakage),h.captureErrors=b.bool(a.params.capture_js_errors),h.siteLevel=b.bool(a.params.site_level_supertag_config),a.params.control_tag_stats_prefix&&q("views."+a.params.control_tag_stats_prefix));a.blocklist&&0<a.blocklist.length&&o.setup();w.fireOnce("config_loaded")};b.d=function(a,c,d){var e=g.console,f=g.KRUXTest;if(!("object"!=typeof e||c>b.debugLevel)){if(f&&f.throwDebugErrors&&
-1>=c)throw"KRUX.d reported an error: "+a;-2>=c?e.error?e.error("KRUX: "+a):e.log("KRUX ERROR: "+a):-1==c?e.warn?e.warn("KRUX: "+a):e.log("KRUX WARNING: "+a):1>=c?e.info?e.info("KRUX: "+a):e.log("KRUX INFO: "+a):e.log("KRUX DEBUG: "+b.predbg+a);d&&e.dir&&e.dir(d)}};b.DART={};b.DART.parseZone=function(a){for(var b={},a=a.split("/"),d=0;d<a.length;d++)switch(d){case 0:b.site=a[d];break;case 1:b.section=a[d];break;case 2:b.subSection=a[d];break;default:b["subSection"+(d-1)]=a[d]}return b};b.DART.keyValues=
function(a){for(var c={},d=a.split(";"),e=0;e<d.length;e++)(a=d[e].match(/(.+)=(.+)/))&&(25<a[1].length||(c[a[1]]=a[2]));return c=b.removeKeys(c,["sz","dcopt",/^ord/,"tile","pos",/uri/,/click/,"ksgmnt",/null/,/undefined/])};b.DART.passDartKvsAsPageAttributes=function(a){var c=b.tagSrcWithMatchingDomain("ad.doubleclick.net","script")||b.tagSrcWithMatchingDomain("ad.doubleclick.net","iframe");if(!c)return{};var c=b.DART.keyValues(c),c=b.removeKeys(c,a),d;for(d in c)"string"==typeof d&&b.pageAttribute(d,
c[d]);return c};b.passDartToKrux=b.DART.passDartKvsAsPageAttributes;b.genUid=function(){var a="abcdefghijklmnopqrstuvwxyz0123456789",b="ABCDEFGHIJKLMNOPQRSTUVWXYZ"+a+"-_",a=a.split(""),b=b.split(""),d=function(a,b){for(var c=b.length,d,e=[];0<a;)d=a%c,a=Math.floor(a/c),e.push(b[d]);e.reverse();return e.join("")},e=(new Date).getTime()/1E3+""+Math.random().toString().substring(3,6)+"",e=e.substring(1,e.length-1),e=e.replace(".","");return function(e){return[d(e,b),d(e,a)]}(parseInt(e,10))};b.get2ndLevelDomain=
function(a){var b=a.match(/https*:\/\/([^:\/]+)/),a=b?b[1].toLowerCase():a.toLowerCase();if(a.match(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/)||-1===a.indexOf("."))return a;return(b=a.match(/([\w\-]{1,249}\.com*\.[a-z]{2})$/))?b[1]:(a=a.match(/([\w\-]{1,250}\.[a-z]{2,3})$/))?a[1]:!1};b.getBrowserLang=function(){var a=g.navigator;return(b.forcedLanguage||a.language||a.systemLanguage||a.browserLanguage||a.userLanguage||"").substring(0,2)};b.getCollectors=function(a){var c=function(a){var c=
H(a);c&&(n._knpix=n._knpix?n._knpix+1:1,n["_kpix_"+b.collectors.length]=c.replace(/\?.+/,""),b.collectors.push(a))},d=function(a){for(var b={w:null,h:null},c=a.attributes,d=0,e=c.length;d<e;d++)"height"==c[d].name.toLowerCase()?b.h=parseInt(c[d].value,10):"width"==c[d].name.toLowerCase()&&(b.w=parseInt(c[d].value,10));if(b.w&&b.h)return b;a.complete&&(b.w=a.width,b.h=a.height);return b};if(a.getElementsByTagName)for(var a=a.getElementsByTagName("img"),e=0,f=a.length;e<f;e++)if(b.isOffsiteTag(a[e])){var g=
d(a[e]);(1===g.w&&1===g.h||0===g.w&&0===g.h)&&c(a[e])}};b.getRequestVal=function(a,c,d){d=b.parseQueryString(d||location.search);return a in d?d[a]:c};var D=function(a,c){c&&(a+="?"+A(c));var d=b._is.ie&&6>=b._is.version?4E3:8E3;a.length>d&&(a=a.substring(0,d));(new Image).src=a;b.backgroundGets.push(a);return a};b.backgroundGet=D;var A=function(a,c){for(var d=[],e,f=b.keyValues(a),c=c||"&",g=0;g<f.keys.length;g++)e=b.toS(f.values[g]),d.push(encodeURIComponent(f.keys[g])+"="+encodeURIComponent(e));
return d.join(c)};b.buildQueryString=A;b.cookie=function(a,b,d){if(1<arguments.length){d=d||{};b||(b="",d.expires=-1);var e="";if(d.expires&&("number"===typeof d.expires||d.expires.toUTCString))"number"==typeof d.expires?(e=new Date,e.setTime(e.getTime()+1E3*d.expires)):e=d.expires,e="; expires="+e.toUTCString();var f=d.path?"; path="+d.path:"",g=d.domain?"; domain="+d.domain:"",h=d.secure?"; secure":"";l.cookie=[a,"=",encodeURIComponent(b),e,f,g,h].join("");return!0}return l.cookie?(e=l.cookie.match(RegExp(a+
"=([^;]+)")))?unescape(e[1]):null:null};b.parseQueryString=function(a){var b=[];if(!a)return b;"?"===a.charAt(0)&&(a=a.substr(1));for(var a=a.replace(/\;/g,"&").replace(/\+/g,"%20"),a=a.split("&"),d=0,e;d<a.length;d++)if(0!==a[d].length){var f="";e="";-1!=(e=a[d].indexOf("="))?(f=decodeURIComponent(a[d].substr(0,e)),e=decodeURIComponent(a[d].substr(e+1))):(f=decodeURIComponent(a[d]),e=!0);b[f]=e}return b};b.init=function(){h.subSection=h.subSection||h.subsection||h.sub_section;h.userAttributes=h.userData||
h.userAttributes;var a=b.get2ndLevelDomain(l.domain);b.context("d",a);h.site=h.site||a;b.isInAdIframe()?n._inifr="true":l.referrer&&(n._kpref_=l.referrer);h.trackSocial&&b.afterLoadCallback(b.trackSocial);"1c6ac852-8938-481a-84b8-4806affc8c13"==h.pubid&&(h.async=!0);a=b.S.get("kuid");a||(a=b.genUid()[0],b.S.set("kuid",a));n._kuid=a;L(h.userAttributes,"_kua_");L(h.pageAttributes,"_kpa_");g.sessionStorage&&(b.sessionViews=(parseInt(g.sessionStorage.kviews,10)||0)+1,g.sessionStorage.kviews=b.sessionViews,
n.sview=b.sessionViews);a=l.getElementsByTagName("script");p.push(0);o.scripts=a.length;o.node=a[a.length-1]};var p=[];p.last=function(){return this[this.length-1]};p.p=p.pop;p.pop=function(){return this.p()};p.s=p.push;p.push=function(a){return this.s(a)};b.inside=p;b.iframeContents=function(a,c){var d=function(a){var c=b.iframeDoc(b._(a));g.addEventListener?c.close():"interactive"==c.readyState?c.close():setTimeout(function(){d(a)},250)};"string"===typeof a&&(a=b._(a));if(!a)return void 0===c?!1:
"";var e=b.iframeDoc(a);if(void 0===c)return e.body?e.body.innerHTML:"";var f="<html><head><title>"+l.title+"</title></head>",f=f+("<body><script>window.KRUX = window.parent.KRUX; window.KRUXSetup = window.parent.KRUXSetup;window.KRUXHTTP = window.parent.KRUXHTTP;<\/script>"+c+"</body></html>");e.open();e.write(f);d(a.id);return!0};b.iframeDoc=function(a){try{if(a.contentDocument)return a.contentDocument;if(a.contentWindow)return a.contentWindow.document}catch(b){return!1}};var H=function(a){try{return a.src}catch(b){return""}};
b.in_array=function(a,c,d){for(var c=b.keyValues(c),e=0;e<c.keys.length;e++)if(d){if(b.toS(c.values[e]).toLowerCase()==b.toS(a).toLowerCase())return!0}else if(c.values[e]==a)return!0;return!1};b.isIgnoredError=function(a){if("en"!=b.getBrowserLang())return!0;for(var c=[/^Permission denied/,/Error loading script/,/Script error\./,/Access is denied/],d=0;d<c.length;d++)if(c[d].test(a))return!0;return!1};b.isInAdIframe=function(){if(g.self==g.top)return!1;var a=0,b=0,d=l.documentElement,e=l.body;if("number"==
typeof g.innerWidth)a=g.innerWidth,b=g.innerHeight;else if(d&&(d.clientWidth||d.clientHeight))a=d.clientWidth,b=d.clientHeight;else if(e&&(e.clientWidth||e.clientHeight))a=e.clientWidth,b=e.clientHeight;return 18E4>=a*b};b.isOffsiteTag=function(a,c){var d=H(a);if(!d)return!1;if(h.allTagsOffsite)return!0;if(!d.match(/https*:\/\//))return!1;var e=b.get2ndLevelDomain(c||l.domain);return b.get2ndLevelDomain(d)!=e};b.kv=function(a,c){return void 0!==c?b._kvs[a]=c:b._kvs[a]||h.userData&&h.userData[a]||
h[a]||null};b.keyValues=function(a){var b=[],d=[],e;for(e in a)a.hasOwnProperty(e)&&(b.push(e),d.push(a[e]));return{keys:b,values:d}};b.literate=function(){if(h.async)return!1;var a=l.readyState;return"complete"==a||"loaded"==a||"interactive"==a&&(b._is.gecko||b._is.webkit)?!1:!0};var i={_kuid:null,_segments:null,_responseData:null,serviceUrl:g.KRUXSetup&&h.segmentsServiceUrl||C+"/user_data/segments",usingCache:!1,cookieLifetime:2592E3,cacheLifetime:14400,realtimeSegmentLifetime:86400,loadOptions:{html5Storage:!0,
varName:"ksgmnts"}};b.Segments=i;i.getEngine=function(){var a=j.HTML5;if(!i.loadOptions.html5Storage||!a.isSupported())a=j.Cookies;return a};i.load=function(a){var a=a||{},b;for(b in a)b in i.loadOptions&&(i.loadOptions[b]=a[b]);var d,a=i.getEngine();null!==a.get(i.loadOptions.varName)&&(i.usingCache=!0,i._segments=a.get(i.loadOptions.varName),d=a.get(i.loadOptions.varName+"_lu"));i._kuid=a.get("kuid");i.realtimeSegments();i.load.called||(i.load.called=!0,!d||(new Date).getTime()/1E3-parseInt(d,36)>
i.cacheLifetime?(d=i.serviceUrl+"?"+A({callback:"KRUX.Segments.callback",pubid:h.pubid}),E(d,!1),i.startTime=(new Date).getTime(),q("segment_requests")):w.fireOnce("segments_loaded"))};b.loadSegments=i.load;i.callback=function(a){q("segment_request_time",(new Date).getTime()-i.startTime,"ms");i._kuid=a.kuid;if(a.segments){i._segments=a.segments.join(",");var a=b.timeStamp(),c=i.getEngine();c.set(i.loadOptions.varName,i._segments,i.cookieLifetime);c.set(i.loadOptions.varName+"_lu",a,i.cookieLifetime);
c.set("kuid",i._kuid);w.fireOnce("segments_loaded")}};i.realtimeSegments=function(){if(r&&r.segments&&r.segments.length){for(var a=[],b=0,d=r.segments.length;b<d;b++)i.isValidSegment(r.segments[b])&&a.push(r.segments[b].segment_id);i._rsegments=a.join(",");i.getEngine().set(i.loadOptions.varName+"_r",i._rsegments,i.realtimeSegmentLifetime)}};i.get=function(){var a=j,b=i._segments||a.HTML5.isSupported()&&a.HTML5.get(i.loadOptions.varName)||a.Cookies.get(i.loadOptions.varName)||"",a=a.HTML5.isSupported()&&
a.HTML5.get(i.loadOptions.varName+"_r")||a.Cookies.get(i.loadOptions.varName+"_r")||"";return b.split(",").concat(a.split(",")).join(",").replace(/^,+/,"").replace(/,+$/,"")};b.getSegments=i.get;i.getKuid=function(){return i._kuid||j.HTML5.isSupported()&&j.HTML5.get("kuid")||j.Cookies.get("kuid")||""};b.getKuid=i.getKuid;i.isValidSegment=function(a){function c(a,c){switch(a){case "user":return b.userAttribute(c)||"";case "page":return b.pageAttribute(c)||"";case "3rd party":return"";default:return""}}
if(a.or&&a.or.length){for(var d=!1,e=0,f=a.or.length;e<f;e++){var g=c(a.or[e].type,a.or[e].name);if(b.in_array(g,a.or[e].values.split(","))){d=!0;break}}if(!d)return!1}if(a.and&&a.and.length){d=0;for(e=a.and.length;d<e;d++)if(f=c(a.and[d].type,a.and[d].name),!b.in_array(f,a.and[d].values.split(",")))return!1}return!0};b.listen=function(a,b,d){return g.addEventListener?a.addEventListener(b,d,!1):g.attachEvent?a.attachEvent("on"+b,d):!1};b.load=function(a){b.literate()?b.listen(g,"load",a):a.call()};
var E=function(a,c,d,e,f){b.loadedScripts.push(a);b.loadScript.sequence=b.loadScript.sequence?b.loadScript.sequence+1:1;var g="kscript_"+b.loadScript.sequence;if(a=H(a)||a)f={id:g,node:e,type:"text/"+(f||"javascript"),src:a},!1===h.async&&c&&b.literate()?(l.__krux_write("<script "+b.buildAttributes(f)+"><\/script>"),"function"==typeof d&&d()):(f.async="true",b.appendTag("script",f),"function"==typeof d&&b.loadScriptCallback(g,d,e))};b.loadScript=E;b.loadScriptCallback=function(a,c,d){var e=b._(a);
e?e.onreadystatechange=e.onload=function(){var a=e.readyState;if(!c.done&&(!a||/loaded|complete/.test(a)))c(d),c.done=!0}:setTimeout(function(){b.loadScriptCallback(a,c,d)},50)};b.loadTemplateTag=function(a,c){b.loadTemplateTag.td={};try{eval("KRUX.loadTemplateTag.td="+a)}catch(d){b.reportError("Error with tag template. "+d.msg+"\n"+a,"email-template-tag");return}var e=b.loadTemplateTag.td;e.before&&e.before(c);var f=/@@([^@]+)@@/g,g=function(a,b){return c[b]?c[b]:a},h="",h="https:"==location.protocol&&
e.sslHost?h+("//"+e.sslHost):h+("http://"+e.host),i=e.path.replace(f,g),h=h+i;if(e.query){for(var i=b.keyValues(e.query),j=0,k=i.keys.length;j<k;j++)e.query[i.keys[j]]=b.toS(i.values[j]).replace(f,g);h+=-1<h.indexOf("?")?"&":"?";h+=A(e.query)}E(h,!1,e.after)};b.makeDate=function(a){if("object"===typeof a&&null!==a&&a.constructor==Date)return a;if(b.toS(a).match(/^[0-9]+$/))return!1;if(b.toS(a).match(/^([0-9]{4})-([0-9]{2})-([0-9]{2})/))return a=b.toS(a).match(/^([0-9]{4})-([0-9]{2})-([0-9]{2})/),
new Date(a[1],a[2]-1,a[3]);if(Date.parse(a)){var c=new Date;c.setTime(Date.parse(a)+6E4*c.getTimezoneOffset());return c}return!1};b.metaTag=function(a){for(var b=l.getElementsByTagName("meta"),d=0,e=b.length;d<e;d++)if(b[d].name==a)return b[d].content;return null};b.onload=function(){if(!b.onloadCalled){b.onloadCalled=!0;n.fired="load";0.05>Math.random()&&(b.appendTag("iframe",{width:0,height:0,src:b.kruxIframeUrl+"bumpCookie"}).style.display="none");if(b.afterLoadFunctions)for(var a=0;a<b.afterLoadFunctions.length;a++)b.afterLoadFunctions[a]();
KRUX2.fireOnce("load_callbacks_finished");b.Storage.expunge(b.S);b.Storage.cleanup(b.S)}};b.onunload=function(){n.fired||(n.fired="unload",b.collectBeacon())};b.onbeforeunload=function(){n.fired||(n.fired="beforeunload",b.collectBeacon())};b.parseJSON=function(a){return g.JSON&&g.JSON.parse?g.JSON.parse(a):(new Function("return "+a))()};b.PM={};b.PM.supported=function(){return g.postMessage||l.postMessage?!0:!1};b.PM.listen=function(a){return!b.PM.supported()?!1:b.listen(g,"message",a)};b.PM.send=
function(a,c){if(!b.PM.supported())return!1;var d=b.toS(c);if(a.postMessage)return a.postMessage(d,"*");if(a.document.postMessage)return a.document.postMessage(d,"*")};b.Provider={};b.Provider.base={id:"base",getUrl:function(){throw"getUrl not implemented for provider: "+this.id;},checkForNew:86400,checkForUpdate:259200,blocking:!1,httpMethod:"script",noData:"no data"};b.Provider.base.cacheKey=function(){return this.id+"_d"};b.Provider.base.run=function(){if(b.S.get(this.cacheKey())||!this.getUrl())return!1;
"script"==this.httpMethod?E(this.getUrl(),this.blocking):"image"==this.httpMethod?D(this.getUrl()):"iframe"==this.httpMethod&&b.appendTag("iframe",{width:0,height:0,src:this.getUrl()});return!0};b.Provider.base.callback=function(a){var c;a?(a=A(a),c=this.checkForUpdate):(a=this.noData,c=this.checkForNew);b.S.set(this.cacheKey(),a,c)};b.Provider.base.getData=function(){var a=b.S.get(this.cacheKey());return a==this.noData?null:b.parseQueryString(a)};b.Provider.serviceUrl=function(a,b){return C+"data."+
(b||"gif")+"?_kdpid="+a};b.readyFunctions=[];b.ready=function(a){b.readyHasRun?a():b.readyFunctions.push(a)};b.readyRun=function(){if(!b.readyHasRun){b.readyHasRun=!0;for(var a=0;a<b.readyFunctions.length;a++)b.readyFunctions[a](g,[])}};b.doScrollHack=function(){if(!b.readyHasRun){try{l.documentElement.doScroll("left")}catch(a){setTimeout(b.doScrollHack,1);return}b.readyRun()}};b.readyBind=function(){if("complete"==l.readyState)setTimeout(b.readyRun,1);else if(l.addEventListener)b.DOMContentLoaded=
function(){l.removeEventListener("DOMContentLoaded",b.DOMContentLoaded,!1);b.readyRun()},b.listen(l,"DOMContentLoaded",b.DOMContentLoaded),b.listen(g,"load",b.readyRun);else if(l.attachEvent){b.DOMContentLoaded=function(){"complete"==l.readyState&&(l.detachEvent("onreadystatechange",b.DOMContentLoaded),b.readyRun())};b.listen(l,"readystatechange",b.DOMContentLoaded);g.attachEvent("onload",b.readyRun);var a=!1;try{a=!g.frameElement}catch(c){}l.documentElement.doScroll&&a&&b.doScrollHack()}};b.readyBind();
b.ready(b.fireReady);var z={},q=function(a,c,d){c=c||1;d=d||"c";"ms"==d&&3E4<c||(z[a]?"c"==z[a].type?z[a].value+=1:b.reportError("Trying to increment a time value - "+a):z[a]={type:d,value:c})},O=function(){if(g.KRUXTest)b.recorderEvents=z;else if(0.05<Math.random())return;var a=[],c;for(c in z)z.hasOwnProperty(c)&&a.push("controltag."+c+":"+z[c].value+"|"+z[c].type);b.backgroundGet(b.eventsUrl+"?q="+a.join(","))};b.removeKeys=function(a,c){for(var d=b.clone(a),e=b.keyValues(d),f=0,g=c.length;f<g;f++)if("string"==
typeof c[f])delete d[c[f]];else for(var h=0,i=e.keys.length;h<i;h++)"test"in c[f]&&c[f].test(e.keys[h])&&delete d[e.keys[h]];return d};b.reportError=function(a){if(window.KRUXTest)throw"reportError:"+a;q("jserror");m.browser&&(q("jserror."+m.browser),q("jserror."+m.browser+"."+m.version))};"function"!=typeof window.onerror&&(window.onerror=function(a,c,d){b.reportError("Error on line #"+d+" of "+c+": "+a,"onerror");return!1});b.timeStamp=function(a){a=a||(new Date).getTime();return Math.round(a/1E3).toString(36)};
var r=null,k={configUrl:"//cdn.krxd.net/config/",chains:{},executedTags:[]};b.ST=k;b.SuperTag=b.ST;b.ST.loadGeo=function(a){var c=b.ST;if("HTML5"==b.S.name){var d=b.S.get("kgeo");if(d){b.ST.geoFromCache=!0;try{b.geo=b.parseJSON(d)}catch(e){b.S.del("kgeo")}w.fireOnce("geo_loaded");return}}d=h.geoUrl||b.geoUrl;b.ST.loadGeo.startTime=(new Date).getTime();q("geo_requests");N()?b.loadScript(d,!a,c.loadGeoSave):("HTML5"==b.S.name&&g.JSON&&b.loadScript(d,!1,c.loadGeoSave),w.fireOnce("geo_loaded"))};b.ST.loadGeoSave=
function(){"HTML5"==b.S.name&&g.JSON&&j.HTML5.set("kgeo",g.JSON.stringify(b.geo),86400);q("geo_request_time",(new Date).getTime()-b.ST.loadGeo.startTime,"ms");w.fire("geo_loaded")};k.callTag=function(a,c){c||(k.sequence=k.sequence?k.sequence+1:1,c="krux_tag_"+a+"_"+k.sequence);if(!r)return!1;var d=k.gimmeTag(a);d.html_id=c;return!1===d?(b.reportError("No available tags for this format: "+a+". If the format is valid, check to make sure you have a non-frequency capped tag at the bottom of the chain.",
"email-config"),!1):k.writeTag(d)};k.callAd=k.callTag;k.deliverPixels=function(){b.pixelsDelivered=0;if(!r)return!1;for(var a=r.tags||[],c=(new Date).getTime(),d=0,e=0;e<a.length;e++){d+=(new Date).getTime()-c;if(d>h.pixelTime)return w.fireOnce("pixels_delivered"),b.pixelsDelivered;var f=a[e];"0x0"==f.format&&k.isValidRules(f)&&!f.started&&(k.writeTag(f),b.pixelsDelivered++)}w.fireOnce("pixels_delivered");return b.pixelsDelivered};k.invisibleTags=function(){};k.getCountry=function(){return b.getRequestVal("krux_country")?
b.getRequestVal("krux_country"):h.forcedCountry?h.forcedCountry:b.geo&&b.geo.country||"Unknown"};b.getCountry=k.getCountry;k.gimmeTag=function(a){for(var c=b.getRequestVal("krux_tagid"),d=0;d<r.tags.length;d++){var e=r.tags[d];if(c&&e.format==a&&e.id==c||e.format==a&&k.isValidRules(e))return e}return!1};k.init=function(){var a=h.superTag;if(void 0!==a.enabled&&!b.bool(a.enabled))return!1;M(h.async);b.ST.loadGeo(h.async);"function"===typeof h.initialize?h.initialize():h.initialize&&w.each(h.initialize,
function(a){a()});w.waitForAll("config_loaded geo_loaded",function(){k.deliverPixels()});!0===h.autoCollect&&KRUX2.waitForAll("load_callbacks_finished pixels_delivered",function(){b.getCollectors(l);b.collectBeacon()});q("views");m.browser&&(q("views."+m.browser),q("views."+m.browser+"."+m.version));return!0};k.isValidCriteria=function(a,c,d){try{d.constructor==Array&&(d=d.toString())}catch(e){}var f=b.toS(d).split(/, */);if(b.toS(c).match(/[<>]/))if(!isNaN(parseInt(a,10))&&!isNaN(parseInt(d,10)))a=
parseInt(a,10),d=parseInt(d,10);else{if("string"!=typeof a||"string"!=typeof d)return null}else if(b.in_array(c,["before","after"])&&(a=b.makeDate(a),d=b.makeDate(d),!a||!d))return null;switch(c){case "=":return b.in_array(a,f,!0);case "!=":return!b.in_array(a,f,!0);case ">":return a>d;case "<":return a<d;case ">=":return a>=d;case "<=":return a<=d;case "before":return a.getTime()<d.getTime();case "after":return a.getTime()>d.getTime();case "matches":var g;try{return g=0===b.toS(d).indexOf("/")?eval(d):
RegExp(d),g.test(a)}catch(h){return!1}case "contains":a=b.toS(a);for(c=0;c<f.length;c++)if(-1<a.indexOf(f[c]))return!0;return!1;default:return b.d("Unrecognized operator: "+c,-1),null}};k.isValidRules=function(a){for(var c=k.isValidCriteria,d=a.rules?a.rules.length:0,e=0;e<d;e++){var f=a.rules[e];f.pass=!0;switch(f.name){case "country":if(c(f.actual=k.getCountry(),f.operator,f.value))break;else return a.rejected="country",f.pass=!1;case "site":if(c(f.actual=h.site,f.operator,f.value))break;else return a.rejected=
"site",f.pass=!1;case "section":if(c(f.actual=h.section,f.operator,f.value))break;else return a.rejected="section",f.pass=!1;case "sub_section":if(c(f.actual=h.subSection,f.operator,f.value))break;else return a.rejected="sub_section",f.pass=!1;case "segment":b.loadSegments();var g=b.getSegments().split(","),i=!1,j=b.getRequestVal("krux_segment");j&&g.push(j);f.actual=g.join(",");for(var j=b.toS(f.value).split(","),l=0;l<j.length;l++)for(var m=0;m<g.length;m++)if(j[l]==g[m]){i=!0;break}if(i)break;
else return a.rejected="segment",f.pass=!1;case "url":if(c(f.actual=location.href,f.operator,f.value))break;else return a.rejected="url",f.pass=!1;default:if(f.name.match(/^userAttributes/)){if(g=f.name.replace(/^userAttributes[0-9]+\./,""),!c(f.actual=h.userAttributes[g],f.operator,f.value))return a.rejected="userAttributes",f.pass=!1}else if(f.name.match(/^pageAttributes/)){if(g=f.name.replace(/^pageAttributes[0-9]+\./,""),!c(f.actual=h.pageAttributes[g],f.operator,f.value))return a.rejected="pageAttributes",
f.pass=!1}else return b.reportError("Unrecognized rule - "+f.name,"email-javascript"),f.pass=!1}}if(a.user_percent&&100*Math.random()>a.user_percent)return a.rejected="user %",!1;c=b.YYYYMMDD();if(a.start_date&&a.start_date>=c)return a.rejected="start date",!1;if(a.end_date&&a.end_date<c)return a.rejected="end date",!1;return a.freq_cap&&(c=b.S.get("l"+a.id),parseInt(c,10)>=parseInt(a.freq_cap,10))?(a.rejected="freq cap",!1):!0};k.makeHtmlDeferred=function(a){var c=[];new b.HTMLParser(void 0,a,{start:function(a,
e,f){var g={},h=a.toLowerCase();c.push("<"+a);for(var a=0,i=e.length;a<i;a++)"script"==h&&"src"==e[a].name?g.krux_deferred_src=e[a].value:g[e[a].name]=e[a].value;"script"==h&&(g.type="text/krux_delayed_script",i=1);0<i?c.push(" "+b.buildAttributes(g)+(f?"/>":">")):c.push(f?"/>":">")},end:function(a){c.push("</"+a+">")},chars:function(a){c.push(a)}});return c.join("")};k.recordAttempt=function(a){a.started=(new Date).getTime();k.executedTags.push(a);a.freq_cap&&b.S.inc("l"+a.id,86400)};k.writeTag=
function(a){a.html_id||(k.sequence=k.sequence?k.sequence+1:1,a.html_id="krux_tag_"+a.format+"_"+k.sequence);b.in_array(a.timing,["asap","ready","onload"])||(a.timing="asap");if(a.template_definition){var c=function(){k.recordAttempt(a);b.loadTemplateTag(a.template_definition,a.params||{})};"onload"==a.timing?b.afterLoadCallback(c):"ready"==a.timing?b.ready(c):c()}else"iframe"==a.method?k.writeTagIframe(a):k.writeTagScript(a,"onload"==a.timing);return a.html_id};k.writeTagIframe=function(a){var c=
a.format.split("x"),d=function(){k.recordAttempt(a);b.iframeContents(a.html_id,a.html)};b.literate()?(l.__krux_write("<iframe "+b.buildAttributes({width:c[0],height:c[1],scrolling:"no",frameborder:0,marginheight:0,marginwidth:0,id:a.html_id})+"></iframe>"),"onload"==a.timing?b.afterLoadCallback(d):"ready"==a.timing?b.ready(d):d()):!b.literate()&&"0x0"==a.format&&(b.appendTag("iframe",{id:a.html_id,width:0,height:0}).style.display="none",d())};k.writeTagScript=function(a,c){k.recordAttempt(a);if(b.literate())c||
0<x.blocklist.length||(b.is.msie||b.is.opera)&&a.html.match(/(__bkframe|google-analytics.com|widgets\.twimg)/)?(l.__krux_write('<div id="'+a.html_id+'">'+k.makeHtmlDeferred(a.html)+"</div>"),o.setup(),k.loadDeferred()):l.__krux_write_real('<div id="'+a.html_id+'">'+a.html+"</div>");else if("0x0"==a.format){a.timing="onload";a.forced_delayed_load=!0;var d=b.appendTag("div",{id:a.html_id});d.style.display="none";d.innerHTML=k.makeHtmlDeferred(a.html);k.loadDeferred()}};k.loadDeferred=function(){for(var a=
l.getElementsByTagName("script"),c=0,d=a.length;c<d;c++){var e=a[c];if(e.getAttribute&&"text/krux_delayed_script"==e.getAttribute("type")){var f=e.cloneNode(!0);f.removeAttribute("krux_deferred_src");f.removeAttribute("language");f.setAttribute("type","text/javascript");o.node=f;p.length=0;p.push(0);if(e.text&&!e.getAttribute("krux_deferred_src"))e.setAttribute("type","text/javascript"),eval(e.text);else{f.timer=setTimeout(function(a){return function(){a.done||(a.done=!0,k.loadDeferred())}}(f),b.scriptTimeout||
2E4);f.onreadystatechange=f.onload=function(){var a=f.readyState;if(!f.done&&(!a||/loaded|complete/.test(a)))clearTimeout(f.timer),f.done=!0,k.loadDeferred()};e.getAttribute("krux_deferred_src")&&f.setAttribute("src",e.attributes.krux_deferred_src.value);e.parentNode.replaceChild(f,e);break}}}};b.Storage={availableEngines:[],getEngine:function(){for(var a=0;a<b.Storage.availableEngines.length;a++)if(b.Storage.availableEngines[a].isSupported())return b.Storage.availableEngines[a];return!1},expunge:function(a){for(var b=
a.keyList(),d=0;d<b.length;d++)null===a.get(b[d])&&a.del(b[d])},cleanup:function(a){for(var b=a.keyList(),d=0;d<b.length;d++){var e=a.get(b[d]).match(/\|~([0-9]+)$/);if(e){var f=a.get(b[d]).replace(/\|~([0-9]+)$/,"");a.del(b[d]);e=(e[1]-(new Date).getTime())/1E3;a.set(b[d],f,e)}}}};var j=b.Storage;j.HTML5={name:"HTML5",isSupported:function(){return g.localStorage?!0:!1},get:function(a){var c=g.localStorage.getItem(a+"__exp");return c&&c<b.timeStamp()?null:g.localStorage.getItem(a)},set:function(a,
c,d){try{g.localStorage.setItem(a,b.toS(c)),d&&g.localStorage.setItem(a+"__exp",b.timeStamp((new Date).getTime()+1E3*d))}catch(e){}},del:function(a){g.localStorage.removeItem(a+"__exp");return g.localStorage.removeItem(a)},inc:function(a,b){var d=j.HTML5.get(a)||0;d++;j.HTML5.set(a,d,b);return d},count:function(){return j.HTML5.keyList().length},clear:function(){return g.localStorage.clear()},keyList:function(){for(var a=[],b=g.localStorage,d=0;d<b.length;d++)b.key(d).match(/__exp$/)||a.push(b.key(d));
return a}};j.availableEngines.push(j.HTML5);j.Cookies={name:"Cookies",cookieName:"KRUXS",cookieExpires:2592E3,isSupported:function(){return navigator.cookieEnabled?!0:!1},get:function(a){var c=j.Cookies._getData();if(a in c){var d=c[a+"__exp"];return d&&d<b.timeStamp()?null:c[a]}return null},set:function(a,c,d){var e=j.Cookies._getData();e[a]=b.toS(c);d&&(e[a+"__exp"]=b.timeStamp((new Date).getTime()+1E3*d));b.cookie(j.Cookies.cookieName,A(e))},del:function(a){var c=j.Cookies._getData(),a=b.removeKeys(c,
[a,a+"__exp"]);b.cookie(j.Cookies.cookieName,A(a))},inc:function(a,b){var d=j.Cookies.get(a)||0;d++;return j.Cookies.set(a,d,b)},count:function(){return b.keyValues(j.Cookies.keyList()).keys.length},clear:function(){b.cookie(j.Cookies.cookieName,null)},keyList:function(){return b.keyValues(b.removeKeys(j.Cookies._getData(),[/__exp$/])).keys},_getData:function(){var a=b.cookie(j.Cookies.cookieName);return null===a?{}:b.parseQueryString(a)}};j.availableEngines.push(j.Cookies);j.Dummy={name:"Dummy",
store:{},isSupported:function(){return!0},set:function(a,c,d){j.Dummy.store[a]=b.toS(c);d&&(j.Dummy.store[a+"__exp"]=b.timeStamp((new Date).getTime()+1E3*d))},get:function(a){if(void 0!==j.Dummy.store[a]){var c=j.Dummy.store[a+"__exp"];return c&&c<b.timeStamp()?null:j.Dummy.store[a]}return null},del:function(a){j.Dummy.store=b.removeKeys(j.Dummy.store,[a,a+"__exp"])},inc:function(a,b){var d=j.Dummy.get(a)||0;d++;j.Dummy.set(a,d,b)},count:function(){return b.keyValues(j.Dummy.keyList()).keys.length},
clear:function(){j.Dummy.store={}},keyList:function(){var a=[],c;for(c in b.removeKeys(j.Dummy.store,[/__exp$/]))a.push(c);return a}};j.availableEngines.push(j.Dummy);b.S=j.getEngine();b.tagSrcWithMatchingDomain=function(a,b){for(var d=l.getElementsByTagName(b),e,f=0,g=d.length;f<g;f++)if(e=H(d[f])){var h=e.match(/^http:\/\/([^\/]+)/);if(h&&("string"!=typeof a&&a.test(h[1])||"string"==typeof a&&-1<h[1].indexOf(a)))return e}return null};b.toS=function(a){return"string"===typeof a?a:null===a?"null":
void 0===a?"undefined":"object"==typeof a?"[object Object]":""+a};b.urlForDomain=function(a){if(b.isInAdIframe())return a.referrer;for(var c=a.getElementsByTagName("base"),d=0,e=c.length;d<e;d++)if(c[d].href)return c[d].href;return a.URL};b.YYYYMMDD=function(a){var b=function(a){return 1==a.toString().length?"0"+a:a};a||(a=new Date);return a.getFullYear()+"-"+b(a.getMonth()+1)+"-"+b(a.getDate())};g.KRUX=b;g.KRUXHTTP=b}(window.KRUXSetup,window,document);
window.KRUX&&function(h,g,l){h.debugLevel=h.getRequestVal("krux_debug",0);var y=h.getRequestVal;g.pubid=y("krux_pubid",g.pubid);g.site=y("krux_site",g.site);g.section=y("krux_section",g.section);g.subSection=y("krux_subSection",g.subSection);g.channels=y("krux_channels",g.channels);g.autoCollect=h.bool(y("krux_autoCollect",g.autoCollect));g.autoInit=h.bool(y("krux_autoInit",g.autoInit));g.superTag=g.superTag||{};l.jQuery&&jQuery.gatling&&(g.async=!0);y("krux_block")&&l.addToBlocklist(y("krux_block"));
y("krux_twinkie")&&h.S.clear();g.pubid&&(!0===h.bool(g.autoInit)&&(h.init(),h.ST.init()),h.bool(g.loadSegments)&&h.loadSegments());h.listen(l,"beforeunload",h.onbeforeunload);h.listen(l,"unload",h.onunload);h.load(h.onload)}(window.KRUX,window.KRUXSetup,window);